#!/bin/bash

# File to modify for fake changes
FILE="progress.log"

# Create file if not exists
touch $FILE

# Array of realistic commit messages for Paysafe project
MESSAGES=(
"setup initial repository configuration"
"add gitignore for python and docker artifacts"
"add flask health endpoint"
"add api version endpoint"
"improve backend error handling"
"add request logging to backend api"
"optimize flask response payload"
"add environment based config loading"
"refactor backend app structure"
"add requirements file for backend"
"pin python dependency versions"
"cleanup unused python files"
"add dockerignore for backend image"
"reduce backend docker image size"
"add multi stage docker build"
"optimize frontend docker image"
"add nginx config for frontend"
"fix frontend routing issue"
"improve frontend ui layout"
"add basic error page for frontend"
"configure kubernetes namespace for paysafe"
"add resource requests and limits"
"add liveness probe for backend"
"add readiness probe for backend"
"fix readiness probe failure issue"
"configure kubernetes services correctly"
"rename backend service for clarity"
"cleanup duplicate service definitions"
"add istio sidecar injection label"
"verify istio proxy injection"
"fix gateway host configuration"
"fix virtualservice host mismatch"
"add http rewrite rule for api path"
"debug 404 issue in istio routing"
"fix no healthy upstream error"
"add destination rule for backend service"
"configure mTLS mode for istio traffic"
"disable strict mTLS for debugging"
"re enable mTLS after fix"
"add argo rollouts crds"
"verify argo rollouts controller running"
"replace deployment with rollout resource"
"add rollout canary strategy config"
"add rollout pause steps"
"adjust canary traffic weights"
"test 1 percent canary traffic"
"test 5 percent canary traffic"
"test 10 percent canary traffic"
"test 25 percent canary traffic"
"test 50 percent canary traffic"
"complete canary promotion"
"abort canary rollout on failure"
"verify rollback behavior"
"add blue green rollout strategy"
"add active service for blue green"
"add preview service for blue green"
"disable auto promotion for blue green"
"test preview service manually"
"fix active service selector issue"
"fix role label mismatch issue"
"cleanup blue green service selectors"
"verify blue green promotion flow"
"promote blue green deployment manually"
"verify zero downtime during promotion"
"rollback blue green deployment"
"test rollback stability"
"cleanup old replicasets"
"verify rollout history"
"convert kubernetes yamls to helm templates"
"add helm helpers for naming"
"add conditional templates for strategies"
"support canary via helm values"
"support blue green via helm values"
"fix helm rendering issue"
"validate helm template output"
"add default values for deployment strategy"
"improve helm chart documentation"
"cleanup helm chart structure"
"final testing on staging cluster"
"prepare demo for review"
"add deployment notes for reviewers"
"final cleanup before submission"
)

# Commit loop
for MSG in "${MESSAGES[@]}"; do
  echo "$(date) - $MSG" >> $FILE
  git add $FILE
  git commit -m "$MSG"
  sleep 1
done

echo "✅ 60 fake commits created successfully"
